### ISSUE TITLE
Differentiating between no-taint perl and taintful Perl

### ISSUE THREAD

**Issue by neilb** [cpan-testers/CPAN-Reporter#102]
As of Perl 5.35.11, Configure lets you decide whether your perl should support taint. The following is how you might build 5.35.11 without taint support:

    ./Configure -des -Dusedevel -Utaint_support

It would be helpful if CPAN::Reporter could distinguish between perls built with and without taint support. I've got two such builds, but if I try and install on the second one, CPAN::Reporter says that I've already submitted a report.

In CPAN::Reporter::History, [`_format_history`](https://metacpan.org/dist/CPAN-Reporter/source/lib/CPAN/Reporter/History.pm#L143) could return a string like

    "$phase $grade $dist_name ($perlver) $platform notaint\n"

If the perl was built without taint support.

Does this make sense, and if so can you give any guidance on the right/best way to do this please? I'll try and get a PR done.

**Comment by neilb** [comment]
I'm thinking it might be something like:

```
my $taint_status = exists($Config{taint_support}) && !$Config{taint_support} ? " notaint" : "";
return "$phase $grade $dist_name ($perlver) $platform$taint_status\n";
```

So a taintful perl would result in a history line exactly the same as now.

**Comment by andk** [comment]
I'm not sure that we want that. The history lines are designed as being lossy. This lossy design was imho well balanced between the number of reports we want to get from each smoker and the relevance of the dimensions the individual testers may champion.

**Comment by neilb** [comment]
> I'm not sure that we want that.

I think we will want it: I have two builds of 5.35.11, one with taint support, and one without. Because of how they're named, the one without taint support wasn't submitting CPAN Testers reports.

**Comment by neilb** [comment]
I'm closing this issue, as my PR which adds the "do you want taint support?" question to Configure has been reverted. I'll be back, with a different change, and will open an issue for that, when ready.

**Comment by andk** [comment]
When the new issue will be opened, I'd like to discuss this in more depth, please CC me on it.
