### ISSUE TITLE
long running perl exposes uninitialized value usage in CPAN::Reporter.

### ISSUE THREAD

**Issue by davehorner** [cpan-testers/CPAN-Reporter#18]
anyone have any idea why or what I should do if a machine won’t return from the Build.PL even though it prints Build.PL exited with 0?  this is happening on a strawberry perl x64 multi-threaded 5.18.2 installing Perl::Critic-1.121.

cpu usage is steady for the process (busy 20%) for a long while; found using smoker, this manual install has been running 20mins.  I killed the most childish perl process after about an hour and it succeeded!  Displaying the uninitialized value warns in the console on the way.

Thank you for your time and wisdom.
--dave
<a href="http://dave.thehorners.com/tech-talk/programming/510-perl-cpan-packaging-notes">http://dave.thehorners.com/tech-talk/programming/510-perl-cpan-packaging-notes</a>

cpan> force notest install Perl::Critic
Database was generated on Fri, 25 Jul 2014 15:07:12 GMT
Running install for module 'Perl::Critic'
Checksum for C:\strawberry\cpan\sources\authors\id\T\TH\THALJEF\Perl-Critic-1.121.tar.gz ok
Scanning cache C:\strawberry\cpan\build for sizes
............................................................................DONE
Configuring T/TH/THALJEF/Perl-Critic-1.121.tar.gz with Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Perl-Critic' version '1.121'

Versions of optional/unlisted/indirect dependencies:

```
File::HomeDir = 1.00
File::Which = 1.09
Readonly::XS = 1.05
Term::ANSIColor = 4.03
```

(C:\strawberry\perl\bin\perl.exe Build.PL exited with 0)
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have_length in numeric gt (>) at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 984.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
Use of uninitialized value $have in sprintf at C:\strawberry\perl\site\lib/CPAN/Reporter.pm line 1004.
CPAN::Reporter: Build.PL result is 'pass', No errors.
  THALJEF/Perl-Critic-1.121.tar.gz
  C:\strawberry\perl\bin\perl.exe Build.PL -- OK
Running Build for T/TH/THALJEF/Perl-Critic-1.121.tar.gz

**Comment by jkeenan** [comment]
Can you identify the version of CPAN::Reporter you were using when you observed these uninitialized value warnings?

**Comment by davehorner** [comment]
report from 2014, this can be closed.
