### ISSUE TITLE
Wishlist:  Have some way for a distribution to flag how it'd like reporting [rt.cpan.org #25203]

### ISSUE THREAD

**Issue by xdg** [cpan-testers/CPAN-Reporter#44]
https://rt.cpan.org/Ticket/Display.html?id=25203

    Though CPAN::Reporter comes with a sensible default for cc_author 'default:yes pass:no' some 
    users insist on setting it to 'yes'.
    
    Some form of mechanism so that I can indicate that I really want pass:no when it comes to my 
    modules would be useful to me.
    
    -- 
    Richard Clamp <richardc@unixbeard.net>

**Comment by eserte** [comment]
As already mentioned in the original RT ticket: this issue is obsolete.

**Comment by xdg** [comment]
Thanks.  Closing.
