### ISSUE TITLE
Action Prompts should not look at PERL_MM_USE_DEFAULT [rt.cpan.org #34524]

### ISSUE THREAD

**Issue by xdg** [cpan-testers/CPAN-Reporter#47]
https://rt.cpan.org/Ticket/Display.html?id=34524

    Currently it seems that it is not possible to take the advantage of
    defining PERL_MM_USE_DEFAULT for automated builds but still send FAIL
    reports manually (or more generally, using the "ask" feature of the
    action prompts at all). So I advocate for not using PERL_MM_USE_DEFAULT
    for action prompts. Rather, if the user wants a fully automated
    reporting machine, he can remove all the "ask" bits from
    CPAN::Reporter's config.ini. Now we also have the possibility to use
    different config.ini files it is also possible to have an environment
    which is fully interactive and one fully automated just by defining
    PERL_CPAN_REPORTER_CONFIG.
    
    Regards,
        Slaven

**Comment by eserte** [comment]
I am not interesting in this feature anymore. Currently it's possible to use the File transport and then handle `fail.*.rpt` and other `.rpt` files differently (i.e. sending the latter automatically via Metabase and doing inspection on the former ones).

**Comment by xdg** [comment]
Thanks.  Closing.
