### ISSUE TITLE
Wishlist: new envariable HARNESS_OPTIONS

### ISSUE THREAD

**Issue by andk** [cpan-testers/CPAN-Reporter#76]
Currently there seems to be only one way to detect whether the tester has run the tests in parallel and that is the order of the tests will then not be alphabetic. But we want to know that in a machine readable form. I think the one additional variable we want to see will be HARNESS_OPTIONS in the reports.

What I learned these days is that the author of a test cannot read the value of HARNESS_OPTIONS because Test::Harness localizes it and does not let the children know about it. Maybe we want to get this changed but for now I'd rather gather data on analysis about it than to change Test::Harness.

No high priority on this one.

Thanks && Best wishes,

**Comment by xdg** [comment]
We should be picking it up if it's visible to CPAN.pm.  See [line 705](https://github.com/cpan-testers/CPAN-Reporter/blob/master/lib/CPAN/Reporter.pm#L705).

However, if parallel testing is being set in the Makefile or Build file when the 'test' target executes, then we wouldn't see it.

I'm inclined to close this, as I don't know what else we can do.

**Comment by xdg** [comment]
I just spot checked and if set, `HARNESS_OPTIONS` will be included in reports.

**Comment by andk** [comment]
Thanks for showing the line! Naively I only checked a tiny sample of reports and not the source code. Now I need to find a plan B. I close the ticket, thanks again!
